### ISSUE TITLE
Nobody find Nivo Slider has big performance issue ?!

### ISSUE THREAD

**Issue by ivanchains** [gilbitron/Nivo-Slider#356]
You guys continue to be amazed by the popularity and success of the Nivo Slider and within the last 24 hours the jQuery plugin has reached the huge milestone of 2 million downloads! .....

But you guys never found that even on your demo site, the Nivo Slider has big performance issue!

Just go to http://demo.dev7studios.com/nivo-slider/, and see your CPU usage. It will come to at least 30% and STAY there. Someone point this is because the slider reloads the images each time they are displayed,that leads to a high amount of http requests when you keep your web page open.(http://support.dev7studios.com/discussions/nivo-slider-jquery-plugin/DH-924141)(http://postimg.org/image/pulc5phwt/)

I don't know if it's the cause. I only know Nivo Slider has big performance issue, what ever windows system I use, what ever browser I use.

yours, 
Ivan

**Comment by vrocks** [comment]
Just noticed this and I am getting complaints from my users about it. Going to have to use a different slider script. I thought it was strange that it loads the banner again and again instead of loading it once and then hiding and unhiding them.

**Comment by MaffooBristol** [comment]
Opening a site shouldn't make your laptop start burning your legs, but that's exactly what's happening with Nivo. It's really not very good, ditch it and move to Slick.

**Comment by giovannipds** [comment]
@MaffooBristol Slick is indeed a very good solution. :)

**Comment by caleuanhopkins** [comment]
We are going to be working on an updated version with performance improvements in the near future, for now we're trying to manage the current issues and PRs submitted on here. I'm going to close this thread for just now but I suspect we may open a new thread in the future for feedback. Thanks for the opinions in the meantime.

**Comment by giovannipds** [comment]
That sounds weird, but ok. =P
