### ISSUE TITLE
nivoslider and https ssl issue

### ISSUE THREAD

**Issue by ianhaney** [gilbitron/Nivo-Slider#403]
Hi

I am using nivoslider in a website and it works perfect on http url but I just got and set up a SSL on the website and now when go to https version of the site, the nivoslider has stopped working and none of the slideshow images are displayed, can anyone help please or had this issue before and how to resolve it

Thank you

Ian

**Comment by ianhaney** [comment]
Sorry just sussed it, I just updated the js googleapis file to use https so is now the following in case anyone else needs to know how to solve it

FROM
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js" type="text/javascript"></script>

TO

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js" type="text/javascript"></script>

**Comment by nyhtml** [comment]
One of our website is using the Gravida theme which has the nivoslider and found "nivo-slider.css" had the issue. Was that you case too?

**Comment by ianhaney** [comment]
I can't remember now, it was so long ago haha. I remember it was a hand coded site and not using WP

**Comment by nyhtml** [comment]
No problem. Have a great day, IanHaney.
